### ISSUE TITLE
`$ pushkin prep` not successful after following migration instructions 

### ISSUE THREAD

**Issue by parkerrobbins** [pushkin-consortium/pushkin#145]
I followed the updated migration instructions on a new experiment I created in a new site (no previous Pushkin files or containers in the directory). The command `$ pushkin setup-transaction-db` ran successfully. (See the error I reported in #144 about `$ pushkin install site`; that may or may not be the source of this error.)

The problem appears to be related to missing files in the experiment I created (although what I created was the most up-to-date `default` template available:

```bash
Problem running migrations.
Failed to set up databases:
        Error: The migration directory is corrupt, the following files are missing: 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js
(node:96543) UnhandledPromiseRejectionWarning: Error: The migration directory is corrupt, the following files are missing: 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js
    at validateMigrationList (/home/parker/.config/yarn/global/node_modules/knex/lib/migrate/Migrator.js:566:11)
    at Migrator.latest (/home/parker/.config/yarn/global/node_modules/knex/lib/migrate/Migrator.js:71:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:96543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:96543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 Database updated. Shutting down...

```

 Full output:
```bash
$ pushkin prep
Problem loading Pushkin's aws deploy configuration file.
package manager:  yarn
resetting experiments.js
Started prepping API for mind
Started loading API controller for mind
Using build-if-changed for  mind_api
Installing dependencies for /home/parker/Desktop/pushkin_aws_test/experiments/mind/api controllers
Started prepping web page for mind
Started loading web page for mind
Using build-if-changed for  mind_web
Installing dependencies for /home/parker/Desktop/pushkin_aws_test/experiments/mind/web page
loaded docker-compose.dev.yml and pushkin.yaml.
Building worker for mind
Building docker image for mind_worker
Updated users/config.yaml to be compatible with default site template v2+.
userMigsDir: /home/parker/Desktop/pushkin_aws_test/users/migrations
userDatabase: localtestdb
Loading migrations for mind
Updated users/config.yaml to be compatible with default site template v2+.
expConfig:
 {"experimentName":"mind","shortName":"mind","apiControllers":{"mountPath":"mind","location":"api controllers","name":"mycontroller"},"worker":{"location":"worker","service":{"image":"mind","links":["message-queue","test_db"],"environment":{"AMQP_ADDRESS":"amqp://message-queue:5672","DB_USER":"postgres","DB_PASS":"example","DB_URL":"test_db","DB_NAME":"test_db"}}},"webPage":{"location":"web page"},"migrations":{"location":"migrations"},"seeds":{"location":""},"database":"localtestdb","logo":"logo512.png","text":"Enter your experiment description here.","tagline":"Be a citizen scientist! Try this quiz.","duration":"","productionDB":"Main"}
Waiting for database to start...
...
Building mind_api from /home/parker/Desktop/pushkin_aws_test/experiments/mind/api controllers
...
Building mind_web from /home/parker/Desktop/pushkin_aws_test/experiments/mind/web page
...
mind_api is built
mind_api is published locally via yalc
...
mind_web is built
mind_web is published locally via yalc
Loaded web page for mind (mind_web)
Added mind to experiments.js
Writing out experiments.js
Installing combined API
Installed combined API
Installing combined front-end
Installed combined front-end
Finished building all experiment workers
updating docker-compose.dev.yml
Writing out front-end config
Setting front-end 'environment variable'
...
...
...
...
...
...
...
...
...
starting migrations....
migAndSeedDirs:
 [
  {
    migrations: '/home/parker/Desktop/pushkin_aws_test/users/migrations',
    seeds: ''
  },
  {
    migrations: '/home/parker/Desktop/pushkin_aws_test/experiments/mind/migrations',
    seeds: '/home/parker/Desktop/pushkin_aws_test/experiments/mind'
  }
]
db: localtestdb
FS-related option specified for migration configuration. This resets migrationSource to default FsMigrations
Problem running migrations.
Failed to set up databases:
        Error: The migration directory is corrupt, the following files are missing: 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js
(node:96543) UnhandledPromiseRejectionWarning: Error: The migration directory is corrupt, the following files are missing: 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js, 20180724101122_create_pushkintemplate_stimulusResponses.js
    at validateMigrationList (/home/parker/.config/yarn/global/node_modules/knex/lib/migrate/Migrator.js:566:11)
    at Migrator.latest (/home/parker/.config/yarn/global/node_modules/knex/lib/migrate/Migrator.js:71:7)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:96543) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:96543) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
 Database updated. Shutting down...
```

@jkhartshorne Let me know which files you would like me to paste in to help, and I will add those.

**Comment by jkhartshorne** [comment]
Ahhh. This is something to add to the FAQ. What's happening is that the database is still configured for your other pushkin site.  Basically, you can't have two implementations of Pushkin on your computer. Rather, you can, but you have to run 'pushkin kill' in between running 'prep' for one and running 'prep' for the other. (Some day it'll be convenient to write it so that you can have two sites on the same computer, but the 'kill' work-around is good enough for now, given our other outstanding todos).

Try running kill and then re-trying the steps above.

**Comment by parkerrobbins** [comment]
@jkhartshorne Do I need to redo all the migration instructions?

**Comment by parkerrobbins** [comment]
@jkhartshorne Update: The answer appears to be no. I ran `$ pushkin kill` and re-ran `$ pushkin  prep` and it was successful. Closing, but opening an issue to add info to FAQ.
