### ISSUE TITLE
pushkin prep throws a 'not a function' error

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#185]
Working through the quickstart for MacOS, the `pushkin prep` step got me:

`TypeError: (0 , _index4.prep) is not a function

    at _callee4$ (/usr/local/lib/node_modules/pushkin-cli/build/index.js:217:37)

    at tryCatch (/usr/local/lib/node_modules/pushkin-cli/node_modules/regenerator-runtime/runtime.js:63:40)

    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/pushkin-cli/node_modules/regenerator-runtime/runtime.js:293:22)

    at Generator.next (/usr/local/lib/node_modules/pushkin-cli/node_modules/regenerator-runtime/runtime.js:118:21)

    at asyncGeneratorStep (/usr/local/lib/node_modules/pushkin-cli/build/index.js:44:103)

    at _next (/usr/local/lib/node_modules/pushkin-cli/build/index.js:46:194)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
`

**Comment by jkhartshorne** [comment]
It's looking like this might be an issue with CLI v. 2.2.9. Though it looks like others didn't necessarily have this problem with that version of the CLI, so I'm still not sure.

**Comment by jkhartshorne** [comment]
I'm no longer having this problem with CLI v. 2.2.10, so I'm closing this.
