### ISSUE TITLE
pushkin start

### ISSUE THREAD

**Issue by jkhartshorne** [pushkin-consortium/pushkin#199]
The pushkin-server on Docker crashes. 

pushkin cli v. 2.2.10
MacOS Monterey
Docker Desktop 4.16.2

> 2023-05-22 15:49:54 yarn run v1.22.19
2023-05-22 15:49:54 $ PORT=80 react-scripts start
2023-05-22 15:49:54 ℹ ｢wds｣: Project is running at http://172.22.0.6/
2023-05-22 15:49:54 ℹ ｢wds｣: webpack output is served from 
2023-05-22 15:49:54 ℹ ｢wds｣: Content not from webpack is served from /usr/src/app/public
2023-05-22 15:49:54 ℹ ｢wds｣: 404s will fallback to /
2023-05-22 15:49:54 Starting the development server...
2023-05-22 15:49:54 
2023-05-22 15:49:55 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2023-05-22 16:02:59 yarn run v1.22.19
2023-05-22 16:02:59 $ PORT=80 react-scripts start
2023-05-22 16:03:01 ℹ ｢wds｣: Project is running at http://172.22.0.2/
2023-05-22 16:03:01 ℹ ｢wds｣: webpack output is served from 
2023-05-22 16:03:01 ℹ ｢wds｣: Content not from webpack is served from /usr/src/app/public
2023-05-22 16:03:01 ℹ ｢wds｣: 404s will fallback to /
2023-05-22 16:03:01 Starting the development server...
2023-05-22 16:03:01 
2023-05-22 15:49:55 Error: error:0308010C:digital envelope routines::unsupported
2023-05-22 15:49:55     at new Hash (node:internal/crypto/hash:69:19)
2023-05-22 15:49:55     at Object.createHash (node:crypto:138:10)
2023-05-22 15:49:55     at module.exports (/usr/src/app/node_modules/webpack/lib/util/createHash.js:135:53)
2023-05-22 15:49:55     at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:417:16)
2023-05-22 15:49:55     at handleParseError (/usr/src/app/node_modules/webpack/lib/NormalModule.js:471:10)
2023-05-22 15:49:55     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:503:5
2023-05-22 15:49:55     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:358:12
2023-05-22 15:49:55     at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
2023-05-22 15:49:55     at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
2023-05-22 15:49:55     at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
2023-05-22 15:49:55 /usr/src/app/node_modules/react-scripts/scripts/start.js:19
2023-05-22 15:49:55   throw err;
2023-05-22 15:49:55   ^
2023-05-22 15:49:55 
2023-05-22 15:49:55 Error: error:0308010C:digital envelope routines::unsupported
2023-05-22 15:49:55     at new Hash (node:internal/crypto/hash:69:19)
2023-05-22 15:49:55     at Object.createHash (node:crypto:138:10)
2023-05-22 15:49:55     at module.exports (/usr/src/app/node_modules/webpack/lib/util/createHash.js:135:53)
2023-05-22 15:49:55     at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:417:16)
2023-05-22 15:49:55     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:452:10
2023-05-22 15:49:55     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:323:13
2023-05-22 15:49:55     at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
2023-05-22 15:49:55     at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
2023-05-22 15:49:55     at context.callback (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
2023-05-22 15:49:55     at /usr/src/app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:55:103 {
2023-05-22 15:49:55   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
2023-05-22 15:49:55   library: 'digital envelope routines',
2023-05-22 15:49:55   reason: 'unsupported',
2023-05-22 15:49:55   code: 'ERR_OSSL_EVP_UNSUPPORTED'
2023-05-22 15:49:55 }
2023-05-22 15:49:55 
2023-05-22 15:49:55 Node.js v20.2.0
2023-05-22 15:49:55 error Command failed with exit code 1.
2023-05-22 16:03:01 Error: error:0308010C:digital envelope routines::unsupported
2023-05-22 16:03:01     at new Hash (node:internal/crypto/hash:69:19)
2023-05-22 16:03:01     at Object.createHash (node:crypto:138:10)
2023-05-22 16:03:01     at module.exports (/usr/src/app/node_modules/webpack/lib/util/createHash.js:135:53)
2023-05-22 16:03:01     at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:417:16)
2023-05-22 16:03:01     at handleParseError (/usr/src/app/node_modules/webpack/lib/NormalModule.js:471:10)
2023-05-22 16:03:01     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:503:5
2023-05-22 16:03:01     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:358:12
2023-05-22 16:03:01     at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
2023-05-22 16:03:01     at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
2023-05-22 16:03:01     at iterateNormalLoaders (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
2023-05-22 16:03:01 /usr/src/app/node_modules/react-scripts/scripts/start.js:19
2023-05-22 16:03:01   throw err;
2023-05-22 16:03:01   ^
2023-05-22 16:03:01 
2023-05-22 16:03:01 Error: error:0308010C:digital envelope routines::unsupported
2023-05-22 16:03:01     at new Hash (node:internal/crypto/hash:69:19)
2023-05-22 16:03:01     at Object.createHash (node:crypto:138:10)
2023-05-22 16:03:01     at module.exports (/usr/src/app/node_modules/webpack/lib/util/createHash.js:135:53)
2023-05-22 16:03:01     at NormalModule._initBuildHash (/usr/src/app/node_modules/webpack/lib/NormalModule.js:417:16)
2023-05-22 16:03:01     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:452:10
2023-05-22 16:03:01     at /usr/src/app/node_modules/webpack/lib/NormalModule.js:323:13
2023-05-22 16:03:01     at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
2023-05-22 16:03:01     at /usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
2023-05-22 16:03:01     at context.callback (/usr/src/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
2023-05-22 16:03:01     at /usr/src/app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:55:103 {
2023-05-22 16:03:01   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
2023-05-22 16:03:01   library: 'digital envelope routines',
2023-05-22 16:03:01   reason: 'unsupported',
2023-05-22 16:03:01   code: 'ERR_OSSL_EVP_UNSUPPORTED'
2023-05-22 16:03:01 }
2023-05-22 16:03:01 
2023-05-22 16:03:01 Node.js v20.2.0
2023-05-22 16:03:01 error Command failed with exit code 1.
2023-05-22 16:03:01 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jkhartshorne** [comment]
Seems to now be working as of this pull request: https://github.com/pushkin-consortium/pushkin-sitetemplate-basic/pull/1#issuecomment-1591786336
